apiVersion: apps/v1
kind: Deployment
metadata:
  name: abraham-deployment
spec:
  selector:
    matchLabels:
      app: abraham-deployment
  replicas: 3
  template:
    metadata:
      labels:
        app: abraham-deployment
    spec:
      containers:
        - name: abraham-deployment
          image: 533267380503.dkr.ecr.us-east-2.amazonaws.com/abrahamecr:latest
          ports:
            - containerPort: 8080
          

---

apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: abraham-service
spec:
  selector:
    app: abraham-service
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: LoadBalancer # type of the service.

